siketyan/ghr

README.md, resources/shell/ghr.bash, resources/shell/ghr.fish, src/cmd/cd.rs, src/cmd/clone.rs, src/cmd/mod.rs, src/cmd/shell.rs
=> feat: Support changing directory into a repo using shell extension

.github/workflows/rust.yml, Cargo.lock, Cargo.toml
=> ci: Build binaries on platforms

resources/shell/ghr.bash, resources/shell/ghr.fish, src/cmd/init.rs
Supports #1 and #14 on init command
=> feat: Support --cd and --open in init command

src/config.rs
=> feat!: Remove config.toml support

Cargo.lock, Cargo.toml, README.md, src/cmd/list.rs, src/cmd/mod.rs, src/main.rs, src/path.rs, src/repository.rs, src/root.rs
=> feat: List all managed repos

src/cmd/clone.rs
Closes #47 
If you want to clone repositories from some lists, you can use `xargs` to achieve that.
=> feat: Support cloning multiple repos at once

src/cmd/path.rs
=> feat!: Support resolving path from URL or patterns

README.md
=> docs: Fix usages of ghr path

.github/workflows/rust.yml, resources/scoop/ghr.json.mustache
=> ci: Auto release to scoop

resources/shell/ghr.bash, resources/shell/ghr.fish
=> feat: Shell completion support for cd / path commands

README.md, resources/shell/bash/ghr.bash, resources/shell/fish/ghr-completion.fish, resources/shell/fish/ghr.fish, src/cmd/shell.rs
=> fix: Fix completion does not work properly

src/application.rs, src/cmd/clone.rs, src/cmd/init.rs, src/cmd/open.rs
=> feat: Open in default application (explorer, open)

README.md, resources/shell/bash/ghr-completion.bash, resources/shell/fish/ghr-completion.fish, src/cmd/profile/list.rs
Added some completion related changes
* Fixed README: `ghr shell bash | source` → `source <(ghr shell bash)`
* Added `--short` option to `ghr profile list` for completions
* Added profile completions to bash + Made open complete repos
* Removed file completions from fish + Added subcommand completions
=> Refine completions (doc fix, profile completions, more fish completions)

Cargo.lock, Cargo.toml, README.md, resources/shell/bash/ghr-completion.bash, resources/shell/fish/ghr-completion.fish, src/cmd/browse.rs, src/cmd/mod.rs, src/platform/github.rs, src/platform/mod.rs, src/url.rs
I haven't tested this on a windows computer, so I appreciate if somebody could check if it works.
=> feat: Add command `browse` for opening a repository on a browser

resources/shell/bash/ghr-completion.bash, resources/shell/fish/ghr-completion.fish, src/platform/github.rs
* Added repo completion to `delete` subcommand
* Replaced deprecated use of `base_url` with `base_uri`
=> Minor chore/fixes

src/cmd/list.rs
I implemented `--full-path` option for my own use, but I'm not sure if it fits the philosophy of the code. I'm just opening this PR as a temporary resort, so feel free to edit or close this 😌 (more than willing to change on my own)
=> [closable] feat: Add `--full-path` option to `list` subcommand

src/cmd/clone.rs
Added a simple retry feature with loops for cloning.
fixes #128
=> Add retry feature to cloning

src/cmd/list.rs
=> feat: Rename --full-path to --path, adding a short alias -p

src/cmd/clone.rs, src/console.rs
=> feat: Cloning multiple repos in parallel

src/cmd/clone.rs, src/git/mod.rs, src/git/strategy/cli.rs
=> feat: Support --single-branch option for cloning

src/cmd/delete.rs
=> feat: Support deleting multiple repos

README.md, src/cmd/mod.rs, src/main.rs
=> feat: Add --quiet / --verbose options in app global

src/cmd/clone.rs, src/git/mod.rs, src/git/strategy/cli.rs
=> feat: Support --origin and --branch options on cloning

src/cmd/clone.rs
=> feat: Disable retrying clone on non-fork repo

src/cmd/add.rs, src/cmd/mod.rs
=> feat: Add `add` command to import an existing repo

README.md, src/cmd/clone.rs, src/cmd/mod.rs, src/cmd/sync/dump.rs, src/cmd/sync/mod.rs, src/cmd/sync/restore.rs, src/git/config.rs, src/git/mod.rs, src/git/strategy/cli.rs, src/git/strategy/mod.rs, src/main.rs, src/path.rs, src/sync.rs
=> feat: Dump and Restore repositories through a TOML file

src/cmd/version.rs, src/main.rs
```
$ ghr version --short
0.4.1
```
=> feat: Short flag for the version command

ghr.example.toml, src/cmd/add.rs, src/cmd/clone.rs, src/cmd/init.rs, src/cmd/profile/apply.rs, src/git/exclude.rs, src/git/mod.rs, src/profile.rs
=> feat: Add entries to .git/info/exclude from the profile

resources/shell/fish/ghr-completion.fish
=> fix: Fix syntax on fish completion

src/cmd/browse.rs
=> feat: browse: Find a URL to open from the current repository

src/cmd/search.rs
Closes #397
See https://github.com/helix-editor/nucleo/issues/9
=> fix: Fix misuse of nucleo-matcher
